- name: "Building {{ ts_container_name }} with url: {{ ts_linux_release }}"
  docker_image:
    name: "{{ ts_container_name }}"
    build:
      path: ../
      args:
        TS_USERNAME: "{{ docker_ts_username }}"
        TS_URL_BZ2: "{{ ts_linux_release }}"
        TS_CONTAINER_NAME: "{{ ts_linux_release }}"
    source: build
  register: image_build

- name: Create a directory if it does not exist
  file:
    path: "{{ docker_template_dir }}"
    state: directory
    mode: '0755'

- name: "Dropping the Docker-compose template file in {{ docker_template_dir }}"
  template: 
    src: docker-compose.yml.j2
    dest: "{{ docker_template_dir }}/docker-compose.yml"
    mode: '0644'

- name: "Stopping Teamspeak3 if running"
  docker_compose: 
    project_src: "{{ docker_template_dir }}"
    state: absent
  #when: image_build.changed

- name: "Starting Teamspeak3"
  docker_compose: 
    project_src: "{{ docker_template_dir }}"
  register: compose_output
  #when: image_build.changed