---
  - name: "Starting deployment of Teamspeak voicechat server"
    hosts: localhost
    gather_facts: False
    become: yes
    vars: 
      ts_linux_release: "{{ lookup('teamspeak3', 'https://www.teamspeak.com/en/downloads/' ) }}"
    roles:
      - teamspeak3 

